import Config

# PORT / VEEJR_DB let you run a second dev instance side by side to test
# federation, e.g.: PORT=4001 VEEJR_DB=veejr_dev2.db mix phx.server
port = String.to_integer(System.get_env("PORT") || "4000")

bind_ip =
  case System.get_env("BIND_ALL") do
    value when value in ["0", "false", "FALSE"] -> {127, 0, 0, 1}
    _ -> {0, 0, 0, 0}
  end

# PHX_HOST, when set (e.g. an ngrok/cloudflare tunnel hostname), makes the app
# generate absolute URLs (magic links) and its federation authority from that
# public HTTPS host instead of localhost. Needed to reach a dev instance from a
# phone: WebCrypto, service workers, and push all require a secure context,
# which browsers grant to https:// (and localhost) but not to a plain LAN IP.
{url_host, url_port, url_scheme} =
  case System.get_env("PHX_HOST") do
    nil -> {"localhost", port, "http"}
    host -> {host, 443, "https"}
  end

# LiveDashboard and the live-reload iframe need script and connect sources the
# application itself does not, so development observes the policy instead of
# enforcing it. Production enforces; see VeejrWeb.ContentSecurityPolicy.
config :veejr, :csp_report_only, true

# Configure your database
config :veejr, Veejr.Repo,
  database: Path.expand("../#{System.get_env("VEEJR_DB") || "veejr_dev.db"}", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :veejr, VeejrWeb.Endpoint,
  # Development listens on all IPv4 interfaces for LAN testing. Set
  # BIND_ALL=false to restrict it to this machine.
  http: [ip: bind_ip, port: port],
  url: [host: url_host, port: url_port, scheme: url_scheme],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "qM48KOT1cDsFZpovCvsniDBuxkWH01ib3aqQ9cr28nPuV8jt/Rrs3eMkY/c+Ujy+",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:veejr, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:veejr, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :veejr, VeejrWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/veejr_web/router\.ex$"E,
      ~r"lib/veejr_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :veejr, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
